######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 28 01:19:36 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += menu.h
SOURCES += main.cpp menu.cpp
