######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 28 01:17:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
