######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 28 01:12:23 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += button.cpp
