######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 28 01:09:36 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
